#!/home/takuto/anaconda3/bin/python3
# SPDX-FileCopyrightText: 2025 Ryuichi Ueda
# SPDX-License-Identifier: GPL-3.0-only

import sys

# 標準入力から数値を読み込んで合計
total = sum(int(line) for line in sys.stdin)
print(total)

